services:
  api:
    build: .
    container_name: vector_db_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1 # 2. Logging flush

    # 3. Override command
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
